# Site settings
title: Ned Efe
email: ned.efe@gmail.com
description: >- # this means to ignore newlines until "baseurl:"
  I created this blog to share things that I am working on and to explore interesting ideas. 

baseurl: "" # the subpath of your site, e.g. /blog
url: "nedefe.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: nedretefe
github_username:  nedefe

excerpt_separator: <!--more-->
future: true
show_excerpts: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
